name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: prepare archives
        run: |
          tar -cvzf symctl-hello-sh-any-any.tar.gz bin/symctl-hello-sh plugins/symctl-hello-sh/README.txt
      - uses: softprops/action-gh-release@v1
        id: release
        with:
          files: |
            symctl-hello-sh-any-any.tar.gz
          body: |
            Release ${{ github.ref_name }}
      - name: update manifest
        run: |
          python .github/workflows/update-manifest.py manifest.json ${{ github.ref_name }} ${{ fromJSON(steps.release.outputs.assets)[0].browser_download_url }}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add manifest.json
          git commit -m "[automated commit] Update manifest.json with release ${{ github.ref_name }}"
          git push origin HEAD:main
